AllCops:
  DisplayStyleGuide: true
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  IgnoredPatterns:
    # 文字列
    - !ruby/regexp /^\s*(['"]|%[qQ]?[(\[{])(.*)['")\]}]$/
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 30
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoredMethods: ['require', 'p', 'puts', 'print']
Style/NumericPredicate:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
